create table cast (created_at date, last_modified_at date, id bigint not null auto_increment, description varchar(255), name varchar(255), cast_type enum ('ACTOR','DIRECTOR','PRODUCER'), primary key (id)) engine=InnoDB;
create table city (created_at date, last_modified_at date, id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table movie (created_at date, last_modified_at date, duration_in_millis bigint, id bigint not null auto_increment, descripion TEXT, image_url varchar(255), name varchar(255), movie_rating enum ('A','U','UA'), primary key (id)) engine=InnoDB;
create table movie_cast (cast_id bigint not null, movie_id bigint not null) engine=InnoDB;
create table movie_features (movie_id bigint not null, features enum ('DOLBY_ATMOS','THREE_D','TWO_D')) engine=InnoDB;
create table movie_languages (movie_id bigint not null, languages enum ('ENGLISH','HINDI','TAMIL','TELEGU')) engine=InnoDB;
create table payment (amount float(53), created_at date, last_modified_at date, id bigint not null auto_increment, reference_id bigint, ticket_id bigint, payment_mode enum ('CC','DC','UPI','WALLET'), payment_status enum ('FAILURE','IN_PROGRESS','REFUND','SUCCESS'), primary key (id)) engine=InnoDB;
create table screen (created_at date, last_modified_at date, id bigint not null auto_increment, theatre_id bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table screen_features (screen_id bigint not null, features enum ('DOLBY_ATMOS','THREE_D','TWO_D')) engine=InnoDB;
create table seat (created_at date, last_modified_at date, id bigint not null auto_increment, screen_id bigint, number varchar(255), seat_type enum ('GOLD','PLATINUM','RECLINER','SILVER'), primary key (id)) engine=InnoDB;
create table show_seat (created_at date, last_modified_at date, blocked_at datetime(6), id bigint not null auto_increment, seat_id bigint, show_id bigint, show_seat_status enum ('AVAILABLE','BLOCKED','BOOKED'), primary key (id)) engine=InnoDB;
create table show_seat_type (created_at date, last_modified_at date, price float(53), id bigint not null auto_increment, show_id bigint, seat_type enum ('GOLD','PLATINUM','RECLINER','SILVER'), primary key (id)) engine=InnoDB;
create table show_table (created_at date, last_modified_at date, city_id bigint, end_time datetime(6), id bigint not null auto_increment, movie_id bigint, screen_id bigint, start_time datetime(6), language enum ('ENGLISH','HINDI','TAMIL','TELEGU'), primary key (id)) engine=InnoDB;
create table show_table_features (show_table_id bigint not null, features enum ('DOLBY_ATMOS','THREE_D','TWO_D')) engine=InnoDB;
create table theatre (created_at date, last_modified_at date, city_id bigint, id bigint not null auto_increment, description TEXT, name varchar(255), primary key (id)) engine=InnoDB;
create table ticket (amount float(53), created_at date, last_modified_at date, id bigint not null auto_increment, user_id bigint, number varchar(255), ticket_status enum ('CONFIRMED','PENDING'), primary key (id)) engine=InnoDB;
create table ticket_show_seats (show_seats_id bigint not null, ticket_id bigint not null) engine=InnoDB;
create table user (created_at date, last_modified_at date, id bigint not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table movie_cast add constraint FKmubobrx5vtcog69c067vb5mbe foreign key (cast_id) references cast (id);
alter table movie_cast add constraint FKiclxo4q0vtqn16tudwy9gg0i0 foreign key (movie_id) references movie (id);
alter table movie_features add constraint FKm2lbxy2185aawc11o1f8db8ov foreign key (movie_id) references movie (id);
alter table movie_languages add constraint FKl9pko34urm8ncqqeabmnad8x foreign key (movie_id) references movie (id);
alter table payment add constraint FKknnc0dgh1i8fkalxi2qcj2bwl foreign key (ticket_id) references ticket (id);
alter table screen add constraint FKilngvwq9jgk3is184yjhkx9k foreign key (theatre_id) references theatre (id);
alter table screen_features add constraint FKhsxt4y5tuoeah50hw31f26bk4 foreign key (screen_id) references screen (id);
alter table seat add constraint FKa20kk7r8mh61c0khpxmx7uqcp foreign key (screen_id) references screen (id);
alter table show_seat add constraint FK6i74j78n2rm115651mji6o8yj foreign key (seat_id) references seat (id);
alter table show_seat add constraint FKi3y7rfhmsvl9glaosxx0l944x foreign key (show_id) references show_table (id);
alter table show_seat_type add constraint FK9mbuh9m3j14sbha37q3bet8n foreign key (show_id) references show_table (id);
alter table show_table add constraint FK2dvdxxjrcpd6t465e6x73tk9k foreign key (city_id) references city (id);
alter table show_table add constraint FKkh8ene42x2qmlna1b690jso52 foreign key (movie_id) references movie (id);
alter table show_table add constraint FKkisp3jkoxjyef53ta3hoteyvy foreign key (screen_id) references screen (id);
alter table show_table_features add constraint FK72ys90e6evxt443mo4ncxh0if foreign key (show_table_id) references show_table (id);
alter table theatre add constraint FKqfrea71qlwgmpbyrmldr5iln3 foreign key (city_id) references city (id);
alter table ticket add constraint FKdvt57mcco3ogsosi97odw563o foreign key (user_id) references user (id);
alter table ticket_show_seats add constraint FKdifsd5gshm8tvh21wirvpbts foreign key (show_seats_id) references show_seat (id);
alter table ticket_show_seats add constraint FKbfdt8c3535o8n02qphcl61w3q foreign key (ticket_id) references ticket (id);
create table cast (created_at date, last_modified_at date, id bigint not null auto_increment, description varchar(255), name varchar(255), cast_type enum ('ACTOR','DIRECTOR','PRODUCER'), primary key (id)) engine=InnoDB;
create table city (created_at date, last_modified_at date, id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table movie (created_at date, last_modified_at date, duration_in_millis bigint, id bigint not null auto_increment, descripion TEXT, image_url varchar(255), name varchar(255), movie_rating enum ('A','U','UA'), primary key (id)) engine=InnoDB;
create table movie_cast (cast_id bigint not null, movie_id bigint not null) engine=InnoDB;
create table movie_features (movie_id bigint not null, features enum ('DOLBY_ATMOS','THREE_D','TWO_D')) engine=InnoDB;
create table movie_languages (movie_id bigint not null, languages enum ('ENGLISH','HINDI','TAMIL','TELEGU')) engine=InnoDB;
create table payment (amount float(53), created_at date, last_modified_at date, id bigint not null auto_increment, reference_id bigint, ticket_id bigint, payment_mode enum ('CC','DC','UPI','WALLET'), payment_status enum ('FAILURE','IN_PROGRESS','REFUND','SUCCESS'), primary key (id)) engine=InnoDB;
create table screen (created_at date, last_modified_at date, id bigint not null auto_increment, theatre_id bigint, name varchar(255), primary key (id)) engine=InnoDB;
create table screen_features (screen_id bigint not null, features enum ('DOLBY_ATMOS','THREE_D','TWO_D')) engine=InnoDB;
create table seat (created_at date, last_modified_at date, id bigint not null auto_increment, screen_id bigint, number varchar(255), seat_type enum ('GOLD','PLATINUM','RECLINER','SILVER'), primary key (id)) engine=InnoDB;
create table show_seat (created_at date, last_modified_at date, blocked_at datetime(6), id bigint not null auto_increment, seat_id bigint, show_id bigint, show_seat_status enum ('AVAILABLE','BLOCKED','BOOKED'), primary key (id)) engine=InnoDB;
create table show_seat_type (created_at date, last_modified_at date, price float(53), id bigint not null auto_increment, show_id bigint, seat_type enum ('GOLD','PLATINUM','RECLINER','SILVER'), primary key (id)) engine=InnoDB;
create table show_table (created_at date, last_modified_at date, city_id bigint, end_time datetime(6), id bigint not null auto_increment, movie_id bigint, screen_id bigint, start_time datetime(6), language enum ('ENGLISH','HINDI','TAMIL','TELEGU'), primary key (id)) engine=InnoDB;
create table show_table_features (show_table_id bigint not null, features enum ('DOLBY_ATMOS','THREE_D','TWO_D')) engine=InnoDB;
create table theatre (created_at date, last_modified_at date, city_id bigint, id bigint not null auto_increment, description TEXT, name varchar(255), primary key (id)) engine=InnoDB;
create table ticket (amount float(53), created_at date, last_modified_at date, id bigint not null auto_increment, user_id bigint, number varchar(255), ticket_status enum ('CONFIRMED','PENDING'), primary key (id)) engine=InnoDB;
create table ticket_show_seats (show_seats_id bigint not null, ticket_id bigint not null) engine=InnoDB;
create table user (created_at date, last_modified_at date, id bigint not null auto_increment, email varchar(255), name varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
alter table movie_cast add constraint FKmubobrx5vtcog69c067vb5mbe foreign key (cast_id) references cast (id);
alter table movie_cast add constraint FKiclxo4q0vtqn16tudwy9gg0i0 foreign key (movie_id) references movie (id);
alter table movie_features add constraint FKm2lbxy2185aawc11o1f8db8ov foreign key (movie_id) references movie (id);
alter table movie_languages add constraint FKl9pko34urm8ncqqeabmnad8x foreign key (movie_id) references movie (id);
alter table payment add constraint FKknnc0dgh1i8fkalxi2qcj2bwl foreign key (ticket_id) references ticket (id);
alter table screen add constraint FKilngvwq9jgk3is184yjhkx9k foreign key (theatre_id) references theatre (id);
alter table screen_features add constraint FKhsxt4y5tuoeah50hw31f26bk4 foreign key (screen_id) references screen (id);
alter table seat add constraint FKa20kk7r8mh61c0khpxmx7uqcp foreign key (screen_id) references screen (id);
alter table show_seat add constraint FK6i74j78n2rm115651mji6o8yj foreign key (seat_id) references seat (id);
alter table show_seat add constraint FKi3y7rfhmsvl9glaosxx0l944x foreign key (show_id) references show_table (id);
alter table show_seat_type add constraint FK9mbuh9m3j14sbha37q3bet8n foreign key (show_id) references show_table (id);
alter table show_table add constraint FK2dvdxxjrcpd6t465e6x73tk9k foreign key (city_id) references city (id);
alter table show_table add constraint FKkh8ene42x2qmlna1b690jso52 foreign key (movie_id) references movie (id);
alter table show_table add constraint FKkisp3jkoxjyef53ta3hoteyvy foreign key (screen_id) references screen (id);
alter table show_table_features add constraint FK72ys90e6evxt443mo4ncxh0if foreign key (show_table_id) references show_table (id);
alter table theatre add constraint FKqfrea71qlwgmpbyrmldr5iln3 foreign key (city_id) references city (id);
alter table ticket add constraint FKdvt57mcco3ogsosi97odw563o foreign key (user_id) references user (id);
alter table ticket_show_seats add constraint FKdifsd5gshm8tvh21wirvpbts foreign key (show_seats_id) references show_seat (id);
alter table ticket_show_seats add constraint FKbfdt8c3535o8n02qphcl61w3q foreign key (ticket_id) references ticket (id);
